---
- hosts: localhost
  connection: local
  tasks:
    - name: "Install software"
      become: true
      package:
        name:
          - git
          - tmux
          - vim
          - zsh
        state: present

    - name: "Pull dotfile repositories"
      git:
        repo: "{{ item.repo }}" 
        dest: "{{ item.dest }}"
        version: "{{ item.version }}"
      with_items:
        - { repo: 'https://github.com/MrXcitement/dot-git.git',
            dest: '~/github/mrxcitement/dot-git',
            version: main }
        - { repo: 'https://github.com/mrxcitement/dot-tmux.git',
            dest: '~/github/mrxcitement/dot-tmux',
            version: master }
        - { repo: 'https://github.com/mrxcitement/dot-vim.git',
            dest: '~/github/mrxcitement/dot-vim',
            version: master }
        - { repo: 'https://github.com/mrxcitement/dot-zsh.git',
            dest: '~/github/mrxcitement/dot-zsh',
            version: master }
