name: actions
on: [push]
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Show repository variable
        run: echo ${{ github.repository }}
      - uses: action/checkout@v2
      - name: Install python3 and pip3
        run: sudo apt install -y python3 python3-pip
      - name: Install hunspell
        run: sudo apt install hunspell hunspell-en-us
      - name: Install pyspelling
        run: pip3 install pyspelling
      - name: Spellcheck files
        run: ./run.sh spellcheck
